// <auto-generated />
namespace Warlock.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddOngoingToSeries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOngoingToSeries));
        
        string IMigrationMetadata.Id
        {
            get { return "201501101715100_AddOngoingToSeries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
